apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: smart-home
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s

    scrape_configs:
      - job_name: 'flask-backend'
        static_configs:
          - targets: ['backend-svc.smart-home.svc.cluster.local:5200']
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: smart-home;node-exporter-svc;http
      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: smart-home;kube-state-metrics;http-metrics
